name: Build Docker image
on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build -t lighthouse-analysis .
